/*
 * Url Manager Service
 * The URL Manager service provides a set of APIs for managing URL rewrites within your application. URL rewriting is a technique used to modify the appearance or structure of URLs while maintaining the functionality and accessibility of the underlying resources.  The URL Manager service offers various operations to create, retrieve, update, and delete URL rewrite configurations. These configurations allow you to define rules that map incoming URLs to different paths or destinations based on specific criteria. By using URL rewriting, you can enhance the user experience, improve SEO (Search Engine Optimization), and manage complex URL structures effectively.  To get started with the URL Manager service, you need to integrate the provided Proto API into your application. The API supports various programming languages and frameworks, making it easy to incorporate URL rewriting functionality into your existing codebase.  Once integrated, you can utilize the different API methods to create, manage, and query URL rewrite configurations based on your application's requirements.  Refer to the API documentation for detailed information on the request and response formats, authentication requirements, and example usage of each API method.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.UrlRewriteLinkRel;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Urlmanager.JSON;

/**
 * UrlmanagerListUrlRewritesByTargetPathsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T16:28:34.214643109Z[Etc/UTC]")
public class UrlmanagerListUrlRewritesByTargetPathsRequest {
  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  private String tenantId;

  public static final String SERIALIZED_NAME_TARGET_PATHS = "targetPaths";
  @SerializedName(SERIALIZED_NAME_TARGET_PATHS)
  private List<String> targetPaths;

  public static final String SERIALIZED_NAME_CONTEXT = "context";
  @SerializedName(SERIALIZED_NAME_CONTEXT)
  private String context;

  public static final String SERIALIZED_NAME_LINK_REL = "linkRel";
  @SerializedName(SERIALIZED_NAME_LINK_REL)
  private UrlRewriteLinkRel linkRel = UrlRewriteLinkRel.UNKNOWN;

  public UrlmanagerListUrlRewritesByTargetPathsRequest() {
  }

  public UrlmanagerListUrlRewritesByTargetPathsRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Required.
   * @return tenantId
  **/
  @javax.annotation.Nullable
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  public UrlmanagerListUrlRewritesByTargetPathsRequest targetPaths(List<String> targetPaths) {
    this.targetPaths = targetPaths;
    return this;
  }

  public UrlmanagerListUrlRewritesByTargetPathsRequest addTargetPathsItem(String targetPathsItem) {
    if (this.targetPaths == null) {
      this.targetPaths = new ArrayList<>();
    }
    this.targetPaths.add(targetPathsItem);
    return this;
  }

   /**
   * Required.
   * @return targetPaths
  **/
  @javax.annotation.Nullable
  public List<String> getTargetPaths() {
    return targetPaths;
  }

  public void setTargetPaths(List<String> targetPaths) {
    this.targetPaths = targetPaths;
  }


  public UrlmanagerListUrlRewritesByTargetPathsRequest context(String context) {
    this.context = context;
    return this;
  }

   /**
   * Optional.
   * @return context
  **/
  @javax.annotation.Nullable
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }


  public UrlmanagerListUrlRewritesByTargetPathsRequest linkRel(UrlRewriteLinkRel linkRel) {
    this.linkRel = linkRel;
    return this;
  }

   /**
   * Get linkRel
   * @return linkRel
  **/
  @javax.annotation.Nullable
  public UrlRewriteLinkRel getLinkRel() {
    return linkRel;
  }

  public void setLinkRel(UrlRewriteLinkRel linkRel) {
    this.linkRel = linkRel;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UrlmanagerListUrlRewritesByTargetPathsRequest urlmanagerListUrlRewritesByTargetPathsRequest = (UrlmanagerListUrlRewritesByTargetPathsRequest) o;
    return Objects.equals(this.tenantId, urlmanagerListUrlRewritesByTargetPathsRequest.tenantId) &&
        Objects.equals(this.targetPaths, urlmanagerListUrlRewritesByTargetPathsRequest.targetPaths) &&
        Objects.equals(this.context, urlmanagerListUrlRewritesByTargetPathsRequest.context) &&
        Objects.equals(this.linkRel, urlmanagerListUrlRewritesByTargetPathsRequest.linkRel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, targetPaths, context, linkRel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UrlmanagerListUrlRewritesByTargetPathsRequest {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    targetPaths: ").append(toIndentedString(targetPaths)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    linkRel: ").append(toIndentedString(linkRel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tenantId");
    openapiFields.add("targetPaths");
    openapiFields.add("context");
    openapiFields.add("linkRel");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to UrlmanagerListUrlRewritesByTargetPathsRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UrlmanagerListUrlRewritesByTargetPathsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UrlmanagerListUrlRewritesByTargetPathsRequest is not found in the empty JSON string", UrlmanagerListUrlRewritesByTargetPathsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UrlmanagerListUrlRewritesByTargetPathsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UrlmanagerListUrlRewritesByTargetPathsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("tenantId") != null && !jsonObj.get("tenantId").isJsonNull()) && !jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("targetPaths") != null && !jsonObj.get("targetPaths").isJsonNull() && !jsonObj.get("targetPaths").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `targetPaths` to be an array in the JSON string but got `%s`", jsonObj.get("targetPaths").toString()));
      }
      if ((jsonObj.get("context") != null && !jsonObj.get("context").isJsonNull()) && !jsonObj.get("context").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `context` to be a primitive type in the JSON string but got `%s`", jsonObj.get("context").toString()));
      }
      // validate the optional field `linkRel`
      if (jsonObj.get("linkRel") != null && !jsonObj.get("linkRel").isJsonNull()) {
        UrlRewriteLinkRel.validateJsonElement(jsonObj.get("linkRel"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UrlmanagerListUrlRewritesByTargetPathsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UrlmanagerListUrlRewritesByTargetPathsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UrlmanagerListUrlRewritesByTargetPathsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UrlmanagerListUrlRewritesByTargetPathsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UrlmanagerListUrlRewritesByTargetPathsRequest>() {
           @Override
           public void write(JsonWriter out, UrlmanagerListUrlRewritesByTargetPathsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UrlmanagerListUrlRewritesByTargetPathsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UrlmanagerListUrlRewritesByTargetPathsRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UrlmanagerListUrlRewritesByTargetPathsRequest
  * @throws IOException if the JSON string is invalid with respect to UrlmanagerListUrlRewritesByTargetPathsRequest
  */
  public static UrlmanagerListUrlRewritesByTargetPathsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UrlmanagerListUrlRewritesByTargetPathsRequest.class);
  }

 /**
  * Convert an instance of UrlmanagerListUrlRewritesByTargetPathsRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

